const data = {
    products: [
        {
            _id: '1',
            name: 'Walmart Gift Card',
            category: 'eGift Card',
            image: '/images/v1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Walmart',
            rating: 4.5,
            numReviews: 10,
            description: 'With a Walmart eGift Card, you get low prices every day on thousands of popular products in stores or online at Walmart.com. You’ll find a wide assortment of top electronics, toys, home essentials and more. Plus, cards don’t expire and you never pay any fees.',
        },
        {
            _id: '2',
            name: 'PlayStation®Store Gift Card',
            category: 'eGift Card',
            image: '/images/v2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'PlayStation®Store',
            rating: 4.0,
            numReviews: 10,
            description: "Your Ultimate Entertainment Code\nDownload the latest games and add ons, watch movies, listen to music, and more.",
        },
        {
            _id: '3',
            name: 'Spotify US Gift Card',
            category: 'eGift Card',
            image: '/images/v3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Spotify',
            rating: 4.8,
            numReviews: 17,
            description: "With Spotify, it’s easy to find the right music for every moment – on your phone, your computer, your tablet and more.\nThere are millions of tracks on Spotify.So, whether you’re working out, partying or relaxing, the right music is always at your fingertips.Choose what you want to listen to, or let Spotify surprise you.\nYou can also browse through the music collections of friends, artists and celebrities, or create a radio station and just sit back.\nWhat’s on Spotify?\nMusic There are millions of songs on Spotify.Play your favorites, discover new tracks, and build the perfect collection.\nPlaylists You’ll find readymade playlists to match your mood, put together by music fans and experts.\nNew Releases Hear this week’s latest singles and albums, and check out what’s hot in the Top 50.",
        },
        {
            _id: '4',
            name: 'adidas US Gift Card',
            category: 'eGift Card',
            image: '/images/v4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'adidas',
            rating: 4.5,
            numReviews: 14,
            description: 'Like the creators who use their gear, adidas is committed to their craft. They believe that sport has the power to change lives. adidas creates innovative products, apparel and footwear for athletes and designs sport-centric streetwear for everyone. Their goal is to promote creativity and encourage anyone to harness the power of sport in their life. Use this gift card at adidas retail locations or online at adidas.com.',
        },
        {
            _id: '5',
            name: 'Ulta Beauty',
            category: 'Beauty',
            image: '/images/v5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Ulta',
            rating: 4.5,
            numReviews: 10,
            description: 'ULTA Beauty is the largest beauty retailer in the United States and the premier beauty destination for makeup, fragrance, skin, hair care products and salon services. Usable up to the balance to purchase goods or services at any participating Ulta Salon, Cosmetics & Fragrance, Inc. (“Ulta”) store or at Ulta.com. Not redeemable for cash unless required by law. This card does not expire, and no fees are assessed on it for any reason. Not a credit or debit card. Safeguard this card. It will not be replaced or replenished if lost, stolen or used without authorization. CARDCO CXVI, Inc. is the card issuer and sole obligor to card owner. CARDCO may delegate its issuer obligations to an assignee, without recourse. If delegated, the assignee, and not CARDCO, will be sole obligor to card owner. Card is distributed by Ulta. However, Ulta is not an obligor to card owner. Purchase, use or acceptance of card constitutes acceptance of these terms. Inquiries: visit http://ulta.com/ulta/guestservices/giftcard.jsp or call 1-888-566-2736.',
        },
        {
            _id: '6',
            name: 'Uber Gift Card',
            category: 'Travel',
            image: '/images/v6.jpg',
            price: 139,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'Get a reliable ride in minutes with the Uber app. By using this gift card, you accept the following terms and conditions: This card is redeemable via the Uber?? or Uber Eats app within the U.S. in cities where Uber or Uber Eats is available. Funds do not expire. The card is non-reloadable and, except where required by law, cannot be redeemed for cash, refunded, or returned. You may be required to add a secondary payment method to use this gift card with the Uber or Uber Eats app. The card is not redeemable outside the U.S. Issuer is not responsible for lost or stolen cards, or unauthorized use. Depending on the state of purchase, this card is issued by Bancorp Card Services, Inc. or The Bancorp Bank. For full terms and conditions and customer service, visit uber.com/legal/gift.',
        },
    ]
}

export default data;